### ISSUE TITLE
Add vCalendar feeds for users for mobile / desktop calendar subscription of jobs taken

### ISSUE THREAD

**Issue by christophmeissner** [coders4help/volunteer_planner#125]
Should be generated per user (on request + caching) accessible via secret (unguessable) urls without auth, so clients are not required to handle auth. This link could be displayed in the profile page and as a footnote in email reminders on taken tasks.

[django-cal](https://github.com/statesofpop/django-cal) might be handy for that, what do you think Maik?

**Comment by maikhoepfel** [comment]
I have yet to be convinced that the volunteers would use calendar feeds. But I'm happy to look into attaching an calendar events with the shift confirmation email? That'll allow most people to add the event to their calendar with one click, right?

**Comment by christophmeissner** [comment]
Don't know how to convice @maikhoepfel on that the volunteers would use calendar feeds without it beeing implemented.

**Comment by jmewes** [comment]
@christophmeissner Give his phone number to a volunteer who desires it.

**Comment by klinger** [comment]
This feature is part of currently discussed draft of a new user interface.

The technical implementation should be discussed here.
