### ISSUE TITLE
Allow logged in user to visit "not logged in" pages too

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#156]
Although it seems to be neat to have a redirect to helpdesk automatically, it's kind of sad to not be able to have a look at "not logged in" pages like landing page (e.g. to have a look for number of registered users and worked hours) or (better looking) /faqs/ (but being stuck at /faq/).

Maybe automatic redirect can be replaced by exchanging "[Login]" with "[Helpdesk]" when authenticated user is detected?

**Comment by christophmeissner** [comment]
Should be fixed by #224

**Comment by klinger** [comment]
Issue should be closed. We have flatpages now. The difference between logged in and non-logged is quite small. The new userinterface will merge non-logged and logged-in  information even further.

**Comment by klinger** [comment]
issue closed, migration of content to flat pages will be implemented in #224, this issue would be a duplicate of the issue.
