### ISSUE TITLE
Make email addresses of user accounts unique

### ISSUE THREAD

**Issue by christophmeissner** [coders4help/volunteer_planner#161]
It's currently possible to use the same email address for multiple user accounts, which leads to confusion with the users. Email addresses should be unique.

**Comment by pitpalme** [comment]
:+1:

**Comment by klinger** [comment]
@srenatus @alper : we need to merge 4b44ad8 to fix it? Or is /develop now fully functional and we can close this issue?

**Comment by srenatus** [comment]
@klinger #296 is merged so this should be fixed on /develop. I'd guess this can be closed.

**Comment by lwm** [comment]
Bump on closing this one?
