### ISSUE TITLE
Volunteer notification on shift assignment

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#205]
If a volunteer is (self- or management-) assigned to a shift a notification 
email should be send to users email address.

Especially when managers can assign users to shifts it's important to notify users about assignment.

**Comment by klinger** [comment]
How far is the implementation of this @christophmeissner ?
You may want describe this as task to and unassign you. Seems to me like an easy/small task for beginners.

**Comment by christophmeissner** [comment]
duplicate of #475
