### ISSUE TITLE
Define shift presentation order

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#208]
Special, mostly one time event, shifts should be enabled to be presented more 
on the spot, i.e. on top of all shifts for the affected facility.

Maybe an optional "important" attribute that pushes selected shifts on top is 
sufficient.

**Comment by christophmeissner** [comment]
Task and Shift objects also could have a priority field (small positive integer) defaulting to 0. Shifts would be ordered by priority and then by their tasks' priority, but shifts' priorities might be changed manually when more fine grained control is required for a single day.
