### ISSUE TITLE
Issues with translation (at least in greek)

### ISSUE THREAD

**Issue by kaposto** [coders4help/volunteer_planner#227]
FAQ page
Volunteers wanted + Filter areas @ Helpdesk
admin web site, notifications, and when adding, text and facility

Also, it looks like notifications are not saved in unicode format

All admin menus and messages basically are translated wrong because the automated translation ignores articles and plural/singular diefferences 

Google Analytics explanation has to be looked at again. Terms and conditions in general.

**Comment by christophmeissner** [comment]
can you provide more details? are those translations missing or wrong?

**Comment by kaposto** [comment]
Hello Chris, sorry for coming back a bit late, but here are some details (not for all, but we could start from here):
First of all, I have run all migrations as of today and I am running the app locally:
1. FAQ page: it is only in german and no entry exists in transifex
2. While logged on, when clicking on my username, the menu appears in german (Benutzerkonto, Hilfe, Ausloggen), although there is greek translation
3. The not logged in page appears in german, although greek translation is available. 

I will try to fix the above and I will come back to you.

**Comment by klinger** [comment]
@kaposto 
1) FAQ page is static and german only. There is no possibility for a translation, the text is hardcoded in a faq.html file. It has to be rewritten to enable translation (this is work in progress). So no issue here.

But:
There seems to be some problem with the translation - at least it seems like there is only a part of the translation available for the menu entries. But some texts have their unique pattern if you choose greek - but thats clearly not greek yet.

**Comment by christophmeissner** [comment]
#224 introduces a flat page app supporting translations. Now static (or missing) content will be replaced/created using this app after next release (scheduled for Sunday, Nov. 8th).

**Comment by christophmeissner** [comment]
Translation process for these pages will probably not involve Transifex any longer, since tx is best used for smaller bits and strings (in the ui) and doesn't work so well for content. Also, translating using tx requires us to do a deployment, which seems odd when changing the FAQ or some other content page. I'd love to hear your suggestions on how to handle translations for those pages.
