### ISSUE TITLE
Org manager cannot edit facility

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#234]
As an organization manager (without super user privileges) I want to edit attributes of a facility (description, etc) at ```/admin/organizations/facility/```.

Opening facility attribute page ```/admin/organizations/facility/$FACILITY_ID``` I'm presented all attributes but no value for "organization" is shown.

When saving an error is raised, stating the value for "organization" is required:

![image](https://cloud.githubusercontent.com/assets/748801/10841399/4943e6c4-7ee9-11e5-925a-aa6ab9e2c030.png)

**Comment by christophmeissner** [comment]
Investigating...

**Comment by christophmeissner** [comment]
This was solved already in develop, created a hotfix to allow faster release of the fixes.
