### ISSUE TITLE
Change email address for automatic notification emails

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#246]
Mails sent to support@volunteer-planner.org should be addressed to a different recipient to differentiate real support emails.

**Comment by christophmeissner** [comment]
What mails do you mean?

**Comment by pitpalme** [comment]
Shift change, shift deletion, and just in case I forgot about a feature sending mails to "support@": most probably those emails too ;)

**Comment by christophmeissner** [comment]
Ah, from:/reply_to: address for responses?

**Comment by christophmeissner** [comment]
Closing dupe in favor of #211

**Comment by pitpalme** [comment]
Spielverderber ;)
