### ISSUE TITLE
Squash and remove old migrations after next release.

### ISSUE THREAD

**Issue by christophmeissner** [coders4help/volunteer_planner#247]
Old migrations can be squashed and removed when current state is deployed to tidy up migrations.

**Comment by klinger** [comment]
I like this idea - we could integrate this in the deployment workflow. 

BUT this only works if we think our installation is the only one out there. This may break other productive installations we dont know, and it will break some development installations (and it can be quite a pain to fill your own development database with sample data to test the installation. Could we provide a sqlite sample database for development?

So I suggest to be very careful with this.

**Comment by klinger** [comment]
/stats/ could be completely removed. there is only migration scripts left, that create and then delete the datamodel.
