### ISSUE TITLE
Stats per facility

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#251]
What about working hour stats per facility, so one (maybe even only managers) can see, how much of this overall working hours have been done in one place?

Nothing important, but maybe interesting?!?

**Comment by christophmeissner** [comment]
totally interesting! +1

**Comment by klinger** [comment]
Its "not a big thing" - it may be worth to describe this further to have a small/easy task ready for new developers. We should not forget the user experience of the site managers to get them to continue to use VP.
