### ISSUE TITLE
Organisation data not saved in Unicode, unable to add country

### ISSUE THREAD

**Issue by kaposto** [coders4help/volunteer_planner#276]
Hello, attached 2 screeshots: The one is what I saw in organisations list after I entered an organisation in greek. The text is not properly displayed.

The second is the message about mixed encodings  when tried to add a country ('illegal mix of collations').

![2b906b00-87f6-11e5-911c-64249f0799ee](https://cloud.githubusercontent.com/assets/150454/11077133/bbfcc992-87fe-11e5-9510-02410dc429ef.png)

![2b938dc6-87f6-11e5-8926-84a286c3e8e5](https://cloud.githubusercontent.com/assets/150454/11077139/c264b16e-87fe-11e5-852c-fccbe95465cf.png)

**Comment by christophmeissner** [comment]
Removed screenshots :-)

**Comment by christophmeissner** [comment]
@pitpalme this might be a configuration problem on staging system. Can you confirm on production or close?

**Comment by kaposto** [comment]
I just tested it on the production site. I tried to enter an organisation in greek and the way it appears afterwards in the web app is as it appears here in the screenshot.

Concerning adding a country, I tried to add greece with greek characters. i got a server error 500.

**Comment by pitpalme** [comment]
Problem exists on prod as well.

And I want to add two things:

"Housten, ..."
and
"I choose the blue pill" :(

Working on it database wise, but it's not going to be trivial.

**Comment by christophmeissner** [comment]
This might be an opportunity to switch to Postgres :-)

**Comment by pitpalme** [comment]
Everyday there's an opportunity to switch database backend :stuck_out_tongue_winking_eye: 

But alas I don't think this is a solution for

```sql
ALTER TABLE `volunteer_beta`.`auth_user` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ERROR 1062 (23000) at line 44: Duplicate entry '**************' for key 'username'
```
(anonymized by me) :stuck_out_tongue_closed_eyes: 

We have usernames with 'ss' and 'ß' which according to 'utf8_unicode_ci' collation are considered equal :tired_face:

**Comment by pitpalme** [comment]
@kaposto Can you try at beta once more. I did a little DB magic and gave it another successful try. But naturally I'm not capable to enter definitely useful and correct information. Switched keyboard to greek layout but I'm not sure it's been "realistic" enough ...

**Comment by kaposto** [comment]
@pitpalme Hello, organisation data now saved in unicode, but short description and organisation info still not displayed correctly on the organisations list.
![screenshot from 2015-11-16 13 05 48](https://cloud.githubusercontent.com/assets/4679848/11181507/e393b084-8c62-11e5-854d-866444c947e8.png)

Do you have a branch on which you are working? Can I pull it?

**Comment by kaposto** [comment]
What about this collation?
http://collation-charts.org/mysql60/mysql604.utf8_general_ci.european.html

**Comment by pitpalme** [comment]
@kaposto I don't have a branch, as I changed things within the database, not the code.

The description and info thing seems to be related to rich text editor and presentation. I'll see how to deal with it :)

The "utf8_general_ci" collation I didn't choose, because it's not recommended and _**can**_ create problems, due to it's incomplete unicode handling. So I decided to go for "utf8_bin" for now, which is not my first choice, but at least safe to use. As it doesn't to any unicode normalization it can't do it wrong (like _general_ does for performance reasons in some situations).

I'll keep you updated and tell the branch as soon as I created one.

**Comment by kaposto** [comment]
@pitpalme OK. Do you have the db modification sql script?

**Comment by kaposto** [comment]
@pitpalme: Tested how greek looked like, it was still displayed strange. Then I found out that  in order to change the encoding of the columns it is not enough to change the encoding of the tables. This script (
[SQLGeneric.txt](https://github.com/coders4help/volunteer_planner/files/40637/SQLGeneric.txt)

produces a script that) changes encoding of all columns by using 'convert'. Could you try it in a beta database so that we make sure it converts correctly german records?

**Comment by kaposto** [comment]
@pitpalme: I checked out in beta.volunteer-planner and it is working perfectly now.
