### ISSUE TITLE
Bitte alphabetisch geordnet anzeigen lassen

### ISSUE THREAD

**Issue by Uppz** [coders4help/volunteer_planner#278]
![problem 1](https://cloud.githubusercontent.com/assets/14153599/11092011/3b8a56ee-8880-11e5-97df-3438e10f3747.png)

Bitte auch die anderen dropdown - auswahlfelder alphabetisch ordnen...

**Comment by christophmeissner** [comment]
In fact, places are sorted alphabetically, but by their area names first and then by place name.

**Comment by klinger** [comment]
@srenatus you want to discuss your commit here before you create a pull request?

What is the desired behaviour here?
a) As now but with an separator between area names and place names?
b) Lists without merge of area names and place names? (Choose area first)
c) A merged list sorted alphabetically?
d) as it is?
