### ISSUE TITLE
Landing page facility list ordering

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#280]
There's several times "Berlin" in facilities listing.
Some facilities are grouped, others presented individually.
I think the grouping and ordering could use some fine tuning, as it's non-obvious to visitors.

![image](https://cloud.githubusercontent.com/assets/748801/11141042/9f449e1c-89e1-11e5-9484-dc75785bff5d.png)

**Comment by christophmeissner** [comment]
Add ordering by place in the query set for this part of the template (or move to front), as the template tag 'regroup' does no ordering by itself (by intention).
