### ISSUE TITLE
Don't include inactive organizations on landing page.

### ISSUE THREAD

**Issue by Uppz** [coders4help/volunteer_planner#281]
Landing page shows test and demo organizations and those which have not been active for a while. Those should be filtered and not shown on the landing page.

**Comment by pitpalme** [comment]
After thinking about it I came to the conclusion we should introduce some kind of "active" attribute to facilities.

Filtering only for "has current shifts" might give the wrong picture if there is some suspension or schedules haven't applied in time. Additionally querying facilities joined with schedule might be too expensive in the future.

**Comment by klinger** [comment]
Or we define a rule about activity: 

"Every facility with at least one shift in the last about 40 days are active."

PRO:
+ This should cover even facilities that only have one event per month. 
+ This is more continuous then shorter time intervals. 
+ This would be automatic - no need for the site adminstrators or the shiftmanager to do something (scales better). And we dont want to do facility related tasks as developers/administrators at all in the future. 

CON:
+ daily job (jobrunner needed) or quite a lot of computation

**Comment by christophmeissner** [comment]
Obsolete by merging (solution of) #454
