### ISSUE TITLE
Wunsch

### ISSUE THREAD

**Issue by MarkPing** [coders4help/volunteer_planner#283]
können wir in der Bestätigungsemail nicht auch die Logindaten des Users mitschicken? damit die Leute diese nicht vergessen??? Falls das schon so ist dann bitte löschen...

**Comment by christophmeissner** [comment]
@MarkPing: Du meinst den username?

**Comment by MarkPing** [comment]
ja usernamen und sein gewähltes Passwort

**Comment by christophmeissner** [comment]
Das Passwort wissen wir nicht. Und selbst wenn wir es wüssten... Kann ja nicht dein Ernst sein, oder?
