### ISSUE TITLE
Administrators can't be added to private shifts

### ISSUE THREAD

**Issue by DaniGr** [coders4help/volunteer_planner#287]
I tried to view the private shifts I made with lageso nacht manager with my DaniGr account and got a 550 error.
When I tried to add DaniGr as lageso nacht facility member this also wasn't possible.
Please let administrators view private shifts as it's very cumbersome having to relog all the time.

**Comment by klinger** [comment]
similar to #301. we should specify what the different roles (user, shiftmanager, admin) should be able to do at #301 and then fix this.

**Comment by Doca** [comment]
you need to assign a user profile for admin also... 
![bildschirmfoto 2015-12-20 um 19 57 58](https://cloud.githubusercontent.com/assets/939359/11919468/01b7ed30-a754-11e5-9754-44d49b46888f.png)

**Comment by DaniGr** [comment]
True, that was it! But it's not intuitive to find this. Please fix, that Admins are also users automatically.
