### ISSUE TITLE
Add weekly timeline

### ISSUE THREAD

**Issue by DaniGr** [coders4help/volunteer_planner#288]
The daily timeline is great, but it would be even better to have a weekly timeline or a date selector - show timeline from... to

**Comment by klinger** [comment]
@DaniGr The daily/weekly timeline is not part of the new user interface anymore. Look at the volunteerplanner slack - theres the link to to the mockups. The designer wants us to comment on his draft until friday. You seem to be  a good proponent for a comment about the timeline.
