### ISSUE TITLE
Button Wish

### ISSUE THREAD

**Issue by MarkPing** [coders4help/volunteer_planner#289]
![p1](https://cloud.githubusercontent.com/assets/14153599/11334980/fa17d012-91d8-11e5-9bb8-5109b1e15481.png)

**Comment by derhuerst** [comment]
@MarkPing 

Just a hint: Please give your issue a relevant and meaningful name to let maintainers easily distinguish it in the list of issues. Also, putting your request in text – not into the screenshot – helps finding the issue later.

**Comment by christophmeissner** [comment]
Won't implement a cancel action since every browser has a back button.
