### ISSUE TITLE
Can sign up in multiple concurrent shifts

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#299]
I was able to sign up in concurrent shifts simultaneously. Shouldn't I get a warning, at least?

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements.

**Comment by klinger** [comment]
Thanks.
I also think there should at least be a warning. I couldnt think of a situation where concurrent shifts should be allowed. But its important to offer https://github.com/coders4help/volunteer_planner/issues/300 to the user first. Should we forbid signing up for concurrent shifts? Opinions?

**Comment by DaniGr** [comment]
Yes forbid please! This was actually the first issue I entered :) Would be more than happy if it would be fixed!

**Comment by numberpi** [comment]
Already fixed in version 1.3.0

**Comment by klinger** [comment]
Did you test it? The release of 1.3 was 14.09.2015. This issue is from 05.12.2015.

**Comment by numberpi** [comment]
Yes and #393 also fixes problems with shifts having a duration <= 1h.
At the moment, you can join two concurrent shifts, if they overlap not more than one hour (to regard transition periods).

**Comment by numberpi** [comment]
But I will open a new issue, that you always get a warning, when you sing in to an overlapping shift. (#395)
