### ISSUE TITLE
User is not provided an overview of shifts he/she has signed up for.

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#300]
If a user has signed up for multiple shifts, he/she probably wants to get an overview of all those shifts.

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements.

**Comment by klinger** [comment]
Thanks. This will definitely come with the new userinterface / workflow. But we can already build a first version of this (especially the business logic) - but we shouldnt invest too much time in the userinterface. Maybe we start here with a new menu entry "my shifts"?

**Comment by Doca** [comment]
yes this will come with new interface definitely! I would estimate in mid feb

**Comment by klinger** [comment]
+ was fixed with pull request #346 
+ on production system since 29th of January 2016
+ (closed)
