### ISSUE TITLE
Separation between admin and frontend users unclear

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#301]
After logging in as an administrator on the backend (http://localhost:8000/admin/) and switching to the frontend (http://localhost:8000/helpdesk/), I am still logged in (as shown at the top right corner). An attempt to sign up for a shift, however, results in an error "User account does not exist.". This can be misleading.

On the front end, admin users should either be:
- Not treated as logged in at all (and thus also not indicated as logged in)
- Treated as a normal user (just with additional privileges)

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements. Thus please apologize if this issue is irrelevant.

**Comment by klinger** [comment]
We have three stages of user rights: users, shiftmanager (only one for a group?) and admins (only a few administrators of the dev team). We have no complete "what should every role be able to do".

Its also (maybe) a problem, that shifts created by an admin cannot be changed by the shiftmanager.

Maybe we further describe here, what the three roles can do?

**Comment by Doca** [comment]
hi @leodabbler you need to assign a user account also to your existing auth account. then i should work
