### ISSUE TITLE
Must navigate very deeply before shift are shown

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#302]
If I am looking for a shift I can participate, I have do dive very deeply into each shift before I see important details like time, work to do, or capabilities required. It would e.g. be useful to get a quick overview of shifts at least on the facility level, without opening each single shift. 

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements. Thus please apologize if this issue is irrelevant.

**Comment by klinger** [comment]
Thanks.

This issue is already worked on - there will be a complete redesign of the the UI / UX of the website for the users. You have to be in the Slack group to join the discussion about it (this week we comment the first draft of the new design).

**Comment by Doca** [comment]
hi there are new slides available from max https://projects.invisionapp.com/share/WC5AM5K4G please see if this is whats needed and mybe update this issue with some screenshots mockups...would be great so that we can bundle tasks
