### ISSUE TITLE
User cannot edit his/her email address.

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#303]
A user can't delete his/her mail address but editing the user name is possible. Usually (i.e. in other web portals) it's the other way round. Mail address should be updateable.

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements. Thus please apologize if this issue is irrelevant.

**Comment by klinger** [comment]
Additional requirements:

+ Editing the e-mail has to be connected to an e-email verification of the the new e-mail. 
+ This should also be connected with a limited time of verification opportunities - the link in the verification e-mail should not be valid forever. (maybe valid for an hour?)

**Comment by Doca** [comment]
we decided to have at least one fixed peace of information because of trolling etc.
