### ISSUE TITLE
User can't delete account

### ISSUE THREAD

**Issue by leodabbler** [coders4help/volunteer_planner#304]
A user also should be able to delete his/her account.

I'm not a user of volunteer-planner, but interested in coding for it and attempting to understand the application and its requirements. Thus please apologize if this issue is irrelevant.

**Comment by klinger** [comment]
Thanks. Definitely important.

We are interested in any kind of contributions. You can work on accepted issues and make pull requests from your fork on this repo. You could meet us at the meetups in Berlin/Germany/Europe http://www.meetup.com/de/coders4help/ and join us on 32C3 in Hamburg/Germany starting from 26.12.2015 to 30.12.15 - or just work on github.

**Comment by klinger** [comment]
see pull request 322. 

No real DELETE, but deactivate and anonymise the data. (see django documentation)

**Comment by klinger** [comment]
fixed by pull request #344 
issue closed.
