### ISSUE TITLE
Add Social Impact Lab as supporter

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#305]
The developers of VP have been granted the possibility to use the Social Impact Lab as coworking space. This should be honored on the supporters flat page.

**Comment by Doca** [comment]
can be done in flatpages

**Comment by klinger** [comment]
Done:
- edited flatpage "/unterstuetzer/"

still TODO:
Ask at social lab, whether we can deliver their logo (put it in our git), and whether there is a preferred "thank you" text.

**Comment by klinger** [comment]
- changed the logo in  flatpage "/unterstuetzer/", its now the official logo of Social Impact Start Stipendiaten. Still necessary to change the link used at the flatpage (necessary to accept pull request to enable VP server to deliver the logo).

**Comment by klinger** [comment]
logo is on server, link is set to logo on server. issue fixed. issue closed.
