### ISSUE TITLE
The documentation needs some diagrams

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#309]
Its important to understand the hierachy of 

+ locations (country, ...),
+ facilites / work places / ..
+ and shifts.

There should be easy to understand diagrams with examples in the documentation for the managers.

**Comment by leodabbler** [comment]
I am currently trying to familiarize myself with the application's architecture and structure. Doing so, I have just started to create some UML class diagrams. Of course I can provide these class diagrams later. I propose to push them to GitHub to a new top-level folder called documentation.

I use Dia (http://dia-installer.de/) for that purpose, as it has some advantages like:
- available for Windows, Linux, Mac
- able to save the models as XML (i.e. text-based, good for versioning in Git or batch edits)
- able export to many formats

**Comment by leodabbler** [comment]
I have just checked in a first UML class diagram of the "organizations" package model and pushed it to my personal repo. Here is a PDF export. Would that be useful for the other packages, too?

[class-diagrams.pdf.zip](https://github.com/coders4help/volunteer_planner/files/72453/class-diagrams.pdf.zip)

**Comment by klinger** [comment]
Very helpful. Used it to understand VP better - and to show it to others. Continue!

**Comment by klinger** [comment]
Documentation is added in /documentation via pull request #342
