### ISSUE TITLE
Using VP in an iframe (schnell-helfen.de)

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#310]
from trini at slack chat volunteerplanner :

https://master.schnell-helfen.de/index.php?id=3225
does not work. Its using VP in an iframe.

**Comment by pitpalme** [comment]
Upgrading to Django 1.9 could give some valuable options about this:

[Clickjacking Protection](https://docs.djangoproject.com/ja/1.9/ref/clickjacking/#)
