### ISSUE TITLE
Better tests needed: Expand the automated tests.

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#314]
We have some automated tests, and all pull requests will be automatically tested by Travis CI. These tests are a good start, but they only cover a small part of the functionality.
There should be additional tests that cover at least all the core functionality.

Why is this important:
- We want to rewrite the user interface - and there will be a lot of changed functionality. There is a high probability that these refactorings will lead to broken functionality (regressions).
- We are so many people working on the code, tests help a lot to avoid defects because of it.

**Comment by leodabbler** [comment]
I totally agree.

**Comment by leodabbler** [comment]
While familiarizing myself with the application, I would like to create automated tests by and by. After that, another person(s) could review the tests.

**Comment by christophmeissner** [comment]
This is either done or not verifiable. Closing.
