### ISSUE TITLE
clean non-logged-in-area - remove static text pages and use flat pages instead

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#316]
The non-logged-in-area does need three forms pages: 
- create a user
- register a shelter / onboarding
- login as a user

All other information (privacy, ..) should be removed and moved to flat pages.

What to do?
- Create/fill flatpages in the production system (including all existing translations)
- change the static links to the flat pages.
- remove the unnecessary code in /non-logged-in-area/

Dependencies: 
- Its important to fix the charset issues first to enable all greek characters in the flat pages. Until that is fixed its better to have the pages here.

**Comment by Doca** [comment]
see drafts of max on https://invis.io/WC5AM5K4G
