### ISSUE TITLE
Remove dependency on cloudflare.com

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#318]
VP does need javascript from cloudflare.com to work. This dependency should be removed.

Steps:
+ Check whether its possible to remove the dependency.
+ Check licence of the included code.
+ (Optional) put a copy of the library of the code in VP and adjust the path to the function calls.
+ (Optional) replace the library with another library that offers similar functions.

Why is it important?
+ The whole content of a website should be delivered from one server (maybe excluding geodata and videos). 
+ better runtime behavior (no waiting for other servers)
+ better uptime because of less dependencies (if another server isnt working or they change the javascript our website dont work)
+ better privacy (no other website can track our users)
+ better security (if one external website got hacked and the javascript is changed our website is automatically hacked too - the user just load the "valid" javascript that can contain every imaginable code)

**Comment by Doca** [comment]
see https://github.com/coders4help/volunteer_planner/issues/319

**Comment by klinger** [comment]
Reopened, only low priority

**Comment by klinger** [comment]
PR #364, closed
