### ISSUE TITLE
Remove dependency on google-analytics.com

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#320]
VP does include trackers and javascript from googleanalytics.com. This dependency should be removed. Trackers are not nice. If we need analytics, we should provide it on our own and dont give our user data to a company.

Steps:
- Check whether its possible to remove the dependency.
- Check licence of the included code.
- (Optional) put a copy of the library of the code in VP and adjust the path to the function calls.
- (Optional) replace the library with another library that offers similar functions.

Why is it important?
- The whole content of a website should be delivered from one server (maybe excluding geodata and videos). 
- better runtime behavior (no waiting for other servers)
- better uptime because of less dependencies (if another server isnt working or they change the javascript our website dont work)
- better privacy (no other website can track our users)
- better security (if one external website got hacked and the javascript is changed our website is automatically hacked too - the user just load the "valid" javascript that can contain every imaginable code)

**Comment by leodabbler** [comment]
Does this help us? Of course, it helps Google.

**Comment by Doca** [comment]
There are of course convenient features why i decided to use google analytics. And initially i wanted to focus on development and not so much on integrating and maintaining external services. If somebody will provide a different external service and does maintenance for at least a year...that would be awesome... There is of course a trade-off but we already extract knowledge how the planner is used

**Comment by asymmetric** [comment]
I heard good things about [piwik](https://piwik.org/)

**Comment by Doca** [comment]
@asymmetric thx for commenting its a totally different PHP/Mysql app which needs its own server
