### ISSUE TITLE
Make it possible to develop VP with a Windows operating system

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#321]
Only low priorty but maybe someone would like to join development but cannot use a unix based computer. We should make it possible (if its possible to enable it without too much effort):

Steps:
+ Check whether the steps in README.md work with Windows operating systems (maybe it works out of the box?).
+ (if needed) Make it run (python modules in /requirements may cause trouble - check it).
+ (if needed) Write documentation (README.md).

**Comment by christophmeissner** [comment]
Would [Vagrant](https://docs.vagrantup.com/v2/why-vagrant/index.html) be an option for you?

**Comment by klinger** [comment]
I dont think that would be enough. A windows user could also use Virtualbox without Vagrant - and run a linux system and install the IDE, Python and the database there.

Vagrant would be nice to have a standardized runtime environment - but for developing using a windows operating system I would like to use my development tools there too - I would want to use Pycharm and my git and other tools i use with other programming languages.

Its really nice to have an IDE like Pycharm change your running system just by changing the source code while running the server. I suppose with vagrant that wouldnt be that easy.

Or how would you configure Vagrant? Could I develop with Pycharm running in Windows? I suppose it wouldnt work well because of the missing libraries.

**Comment by klinger** [comment]
Its now possible to run the development environment in Docker (a database container and a web container). Its now possible to develop. Closed.
