### ISSUE TITLE
Migration from Python 2 to Python 3?

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#322]
Are there any design decisions that force us to use Python 2 instead of Python 3?
What are the advantages of using Python 2?
How much work is it to migrate to Python 3?

Lets discuss it and then decide whether we want to migrate (issue) this is or not (wontfix).

**Comment by Doca** [comment]
Some libraries are still not fully implemented on py3 i guess. If somebody who wants to use python 3 would like to check it...just do it and we could migrate. But right now there are way more important issues to solve in my opinion

**Comment by klinger** [comment]
We should check it again. On the long term Python 2 would not be supported by Django (starting from Django 2.0). If not possible to migrate yet - Django 1.11 still works with Python 2.

**Comment by christophmeissner** [comment]
Obsolete.
