### ISSUE TITLE
Manager can't delete shifts

### ISSUE THREAD

**Issue by DaniGr** [coders4help/volunteer_planner#328]
When I try to delete shifts with my manager account where people have already signed in I get the following error:
![screenshot 2015-12-15 13 26 13](https://cloud.githubusercontent.com/assets/14186765/11810658/edf90676-a32f-11e5-9b7d-23237b45b2b5.png)

The shift has been created and added with the same manager account, not with my admin account.

**Comment by klinger** [comment]
On my local maschine I used as setup:
+user is member of "Einrichtung" as manager
+user has a role shiftmanager (with all rights starting with scheduler; not even with the rights of scheduletemplates). And I create a shift with this user for today and delete it directly afterwards with the same account.

I suppose we just have to edit the rights in the production system and add the right "Scheduler - Schichthelfer - User can delete shift helper".

I can reproduce your error when I remove this right, sign up one user to the shift and delete the shift. I get following error:

Deleting the shift 'Wäsche waschen - Facility 100 (Jan. 20, 2016, 4:05 p.m. - Jan. 20, 2016, 4:05 p.m.)' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects: shift helperd - i

We can see in leodabblers documentation diagrams that "shift helper" is just the link between shift and user account and can be deleted, it doesnt delete the user account.


Just add the right at the production system to the group for Einrichtung-Managers?

**Comment by DaniGr** [comment]
Sören, terribly sorry! I forgot an essential thing in the description: It does work with normal shifts but NOT with shifts where people have already signed in! Will edit the issue accordingly.

**Comment by klinger** [comment]
Cannot be done by one click. We have to do a bit more:

We want to enable the shift manager to delete shifts - even if somebody has signed in. This should ONLY be allowed for shifts starting from today (and for the future, NOT for the past).

(Giving the right would allow shift managers to delete shifts in the past).

**Comment by DaniGr** [comment]
I have some more information: it seems the shift manager needs to have the right "schichthelfer" to delete those shifts. I now deleted the shifts using my admin account but it is still a high priority issue.
