### ISSUE TITLE
Using OpenStreetMap

### ISSUE THREAD

**Issue by asymmetric** [coders4help/volunteer_planner#329]
Have you considered switching to OSM? I think that from an ethical point of view it makes a lot more sense, but I have no direct experience with their API.

Would love to help, in case you decide to switch.

**Comment by Doca** [comment]
could do so...but priorities are now to work on bugs at least for me. If someone would like to take this up...?

**Comment by klinger** [comment]
see issue #297
(personally strongly support this)

**Comment by asymmetric** [comment]
I will have some time to take a look at implementing this after the holidays
