### ISSUE TITLE
shiftmailer: better statistics

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#343]
In the Excel file: now its only possible to see the number of people participating in a shift. Its not possible to see, how many could participate. (better statistics)

**Comment by leodabbler** [comment]
Could you explain this a little bit further? Refer to the attachment to see what I currently get.

![bildschirmfoto vom 2016-01-31 15 15 37](https://cloud.githubusercontent.com/assets/16061535/12702566/835aedac-c82d-11e5-997b-b5a09b4054f5.png)

**Comment by klinger** [comment]
it would be good to have
column I: max number (in row 3 its 25)
and
column J: number of people who participate (its 2)
cIn this way people who want statistics can just summarize all values in the columns I and J
(if you have another idea for this, its also possible to do it),

**Comment by leodabbler** [comment]
have done it as proposed (ok, not exactly)
![bildschirmfoto vom 2016-02-03 09 11 45](https://cloud.githubusercontent.com/assets/16061535/12776440/3720e2c2-ca56-11e5-84e9-b35f00583431.png)

**Comment by leodabbler** [comment]
I have provided a pull request 6 weeks ago, please check it

**Comment by klinger** [comment]
has been merged. this enhancement has been added by leodabbler. (closed)
