### ISSUE TITLE
Open Street Maps link does not work at shelter overview

### ISSUE THREAD

**Issue by Doca** [coders4help/volunteer_planner#347]
Link redirect doesn't work properly

**Comment by asymmetric** [comment]
What's a URL I can test this out at?

**Comment by Doca** [comment]
Hi thanks for asking. If you logged in and then click on a shelter https://volunteer-planner.org/helpdesk/
![bildschirmfoto 2016-01-29 um 19 06 17](https://cloud.githubusercontent.com/assets/939359/12683797/974e8f08-c6bb-11e5-8396-5333441936cf.png)

If you clicked two locations after another this bug appears (Mac,Firefox)

**Comment by asymmetric** [comment]
I clicked on two locations and hovered over "Show on map", and the links appear correctly on both of them.

![gifrecord_2016-01-29_193138](https://cloud.githubusercontent.com/assets/101816/12684420/20d1206c-c6bf-11e5-96b9-c9239cd5f763.gif)


Not sure if I understand the repro conditions though.

**Comment by Doca** [comment]
oh okay...no the map which opens... shows the first location only...so its kind of displaced... can you see it?

**Comment by asymmetric** [comment]
Sorry, I don't understand. Are you referring to this:

![screenshot from 2016-01-29 20-51-02](https://cloud.githubusercontent.com/assets/101816/12686486/24652204-c6ca-11e5-9be9-781728d7f6c1.png)

**Comment by klinger** [comment]
This is a bit strange. I corrected the value to Gürtestr. and now it works.

**Comment by klinger** [comment]
Issue fixed via correcting the syntax of adress entries in the adress fields of the NUKs. Closed.

**Comment by asymmetric** [comment]
By the way, I added the Wrangelstr. NUK to OSM as a location, so you can search for, e.g. "NUK Wrangelstr" (and variations) and you would find it.

I suggest we do this for other places too, as that helps OSM as well as us.
