### ISSUE TITLE
users should get an email about changed shifts.

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#352]
If a manager changes a shift, the already signed in users should get an email that at least contains the details of the new shift. (It would be good to know the details before the change too to identify the shift that changed).

**Comment by pitpalme** [comment]
@klinger
Clarification request: Which of [this template's](/coders4help/volunteer_planner/scheduler/templates/shift_modification_notification.html) information shall be extended by what exactly? I'm too dumb at the moment, to see, what's missing.

Regards,
Peter

**Comment by klinger** [comment]
its not about extending, its about getting an email at all. The template seems to be perfect. At least in english.

The total e-mail system seems not to be totally consistent, the texts should be localized too. But as a first step, we should send some emails ;-).

**Comment by pitpalme** [comment]
You're right about localization.

Nevertheless, according to [this code](/coders4help/volunteer_planner/blob/develop/scheduler/signals.py#L95) the mail should be sent and in my test I saw the mail in my console (because of 'django.core.mail.backends.console.EmailBackend') 😲
