### ISSUE TITLE
shiftmailer sends excel - this should be printable to A4 sheets

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#368]
The extension of the information in the excel sheet sent by the shiftmailer may have broken the page layout. The Excel sheet should be printable to to A4 paper sheets.

Please check whether it is still possible to print on A4.
Maybe change the layout or remove some unneeded colums.

@pitpalme can maybe tell whether there are columns that can be deleted.

**Comment by leodabbler** [comment]
I have shrunk the columns a bit. I have tested this with LibreOffice Calc only, please retest with Excel and adjust the columns when needed. Currently, the columns Von, Bis, ID, RK and FZ seem to be unused and filled with fixed values, see line 45 of excel_renderer.py:

`for cidx, val in enumerate([i, first_name, last_name, '', '', '-', '-', '-']):`

**Comment by pitpalme** [comment]
@leodabbler: Thanks for the PR.
Before merging it, let's do the job properly :)
I've had a look at source code and it's rather unlikely, we'll implement the three status indicators on the near future.

I'd be happy, if you'd simply remove the three static columns for "ID, "RK" and "FZ" in your branch.
"Von" and "Bis" might be of limited use, so we can, I think, leave it for now.

The PR should be updated automatically, once you commit the change to your branch.
I'll than test with Excel on my side and accept the PR, once the result is acceptable :)

Regards,
Peter

**Comment by leodabbler** [comment]
Done as proposed.
