### ISSUE TITLE
bug in list of shifts: wrong shifts are shown

### ISSUE THREAD

**Issue by klinger** [coders4help/volunteer_planner#373]
Bug: You can see in "my shifts" 15. April a shift you have worked on 15. March as a shift for today.

Shifts in "my shifts" are filtered: Shifts today, tomorrow and so on.

But the filters are not complete.

The filter for shifts only looks at the day (month and year are ignored).

**Comment by numberpi** [comment]
try

shift__starting_time__day=date.today().day,
shift__starting_time__month=date.today().month,
shift__starting_time__year=date.today().year

**Comment by klinger** [comment]
fixed by PR #387
