### ISSUE TITLE
Display mail address of volunteers to managers of restricted shifts

### ISSUE THREAD

**Issue by numberpi** [coders4help/volunteer_planner#390]
**Motivation:**

Hallo liebes Volunteer-Planner-Team,
es passiert immer mal, dass sich Leute bei uns für Schichten eintragen wollen, ohne dass sei sich vorher bei uns melden. Allerdings ist es mir wichtig, zuerst mit den Leuten gesprochen zu haben, bevor ich Sie (insbesondere mit Kindern) aber auch allgemein mit Geflüchteten arbeiten lasse. Deshalb sind zunächst alle Schichten bei uns zugangsbeschränkt.

Kann ich irgendwie auch die E-Mail-Adressen der Leute einsehen, die sich eintragen wollen? Ich bekomme ja jedes mal wenn jemand ohne Zugangsberechtigung auf 'mitmachen' klickt eine Meldung. Dann würde ich die Leute gern anschreiben, wie es weitergehen kann.

**Tasks:**
- Include volunteer mail address into notification / mail sent to shift manager

**Comment by numberpi** [comment]
See organizations/templates/manage_members.html

**Comment by klinger** [comment]
fixed.
