### ISSUE TITLE
Migration from Django version 1.8 to 1.10?

### ISSUE THREAD

**Issue by CokkocZateki** [coders4help/volunteer_planner#404]
Hi

Is it possible to Port to Django 1.10 instead of current verison

thx

**Comment by klinger** [comment]
also see: https://github.com/coders4help/volunteer_planner/issues/335

I personally would like to have a PR for the update of Django - but look at 
https://www.djangoproject.com/download/
Django 1.8 has longer support than Django 1.10.
The next version we really need and should migrate to is 1.11 - but 1.11 is not yet released.

Why do you suggest to update? Is there a feature we may need?

**Comment by klinger** [comment]
closed
