### ISSUE TITLE
Open for PR?

### ISSUE THREAD

**Issue by minthemiddle** [coders4help/volunteer_planner#408]
I saw that volunteer-planner.org got updated and restarted. Is the project open to individual PRs? Or do you have a team coordinating bigger chunks of improvement? If yes, how to get in touch with them?

**Comment by Doca** [comment]
Hi I think we worked together already 2015 right? So I see you are still in coders4help.slack.com feel free to join :-)

**Comment by christophmeissner** [comment]
Every improvement is very welcome, just fork and create a PR. Since this project was shelved for quite some time, we'll probably need some time for assessing the currently open issues and update the project to a resonable django version.

**Comment by christophmeissner** [comment]
Any suggestion or feature: just open an issue and we'll discuss it. This way, we can keep all ideas in one place.
