### ISSUE TITLE
Zusatzidee / Mögliche Probleme bei der Handynutzung / FAQ und Unterstützer Link

### ISSUE THREAD

**Issue by uppzz** [coders4help/volunteer_planner#418]
Zusatzidee (war ein Grund wieso die vom LAF den planner nicht nutzen wollten):
    • Könnte man im Benutzerkonto des Users noch ein Feld hinzufügen für spezielle Informationen über den Benutzer?
        ◦ wie z.B. Telegramm username (viele kommunizieren über das tool und so könnten die manager direkt die leute im telegramm anschreiben)
        ◦ oder Habe auto für 3 Personen

Mögliche Probleme bei der Handybenutzung
    • Zeitstrahl als default eingeklappt lassen?
        ◦ Man kann auf dem Zeitstrahl selber nicht nach unten scrollen
            ▪ nur wenn man rechts aussen am 2mm Rand scrollt, kommt man zu den Schichten wo man sich eintragen kann
    • Um sich in eine Schicht einzutragen muss man auf dem Handy den Schichtplan nach rechts wischen. 
        ◦ Wenn man bei der Ausgabe: Die Spalten "Benutzer" und "Du" tauschen würde, könnte man einen Teil des Mitmachen Buttons auch auf kleinen Handys schon halb sehen ohne das handy drehen zu müssen.
    • Ist es möglich, das Burgermenü auch anzuzeigen, wenn man sich in einer Schicht (da wo man sich via Button einträgt) befindet? 
        ◦ Dann muss man nicht erst zurück, um in sein Profil zu kommen, wo man sich seine eingetragenen Schichten angucken kann.
    • Wäre es möglich den Link im Burgermenü "Meine Schichten" nicht unter dem Usernamen zu "verstecken" sondern offensichtlich direkt zu oberst? 
        ◦ Ich glaube nicht viele haben bis jetzt gesehen, dass sie dort ihre schichten angucken können.

Deine Schichten
Regionen v
F.A.Q.
Deutsch v
Benutzername v

Ist mir so aufgefallen:
    • FAQ bearbeiten. Dort stehen falsche Daten drin (Es gibt zurzeit keine Schichten usw)
    • Footer: Link Unterstützer
        ◦ Seite nicht geholfen

**Comment by pitpalme** [comment]
Will be split into separate issues / feature request.
