### ISSUE TITLE
Save location filters of the user in session

### ISSUE THREAD

**Issue by Doca** [coders4help/volunteer_planner#430]
![Bildschirmfoto 2022-03-17 um 14 00 07](https://user-images.githubusercontent.com/939359/158813847-f794e101-acad-41ba-8624-1ffe55088b6b.png)

- [ ] Create (logical or) filters for countries and areas 
- [ ] save this filter into a cookie so that the user don't have to set the filters again if he revisites the scheduler

**Comment by christophmeissner** [comment]
Please add a description to the issue.

**Comment by Doca** [comment]
discussed it already via slack and on the phone as far as i know
