### ISSUE TITLE
Problem beim eintragen in die gleiche Nachtschicht 3 Tage hintereinander

### ISSUE THREAD

**Issue by uppzz** [coders4help/volunteer_planner#432]
Wenn man sich in folgende Schichten einträgt
am 14.3. in die schicht 14,5, 00:00 - 15,3, 7:00
am 15,3, in die schicht 15,3, 00:00 - 16,3, 7:00
am 16,3, in die schicht  16,3, 00:00 - 17,3, 7:00

bekommt man ma 16,3, folgenden Fehler angezeigt... man kann sich momentan nur jeden 2. Tag in diese schichten eintragen. 

![Selection_449](https://user-images.githubusercontent.com/46990472/158140851-a79999a8-ca43-4a41-8d81-6a92a15cea10.jpg)

**Comment by christophmeissner** [comment]
What is the expected behavior?

**Comment by pitpalme** [comment]
Still active?

**Comment by pitpalme** [comment]
Solved
