### ISSUE TITLE
Admin: Einrichtungsmanager sehen Einträge "Organisationen" und "Organisationsmitglieder" ohne Inhalt

### ISSUE THREAD

**Issue by uppzz** [coders4help/volunteer_planner#435]
![Selection_451](https://user-images.githubusercontent.com/46990472/158168665-22fa1ddf-02ad-4400-a442-0a7113241d16.jpg)

Einrichtungsmanager sehen Organisationen - und Organisationsmitglieder Ordner ohne Inhalt, obwohl Inhalt da wäre.. Sollen sie die Organisationsmitglieder einsehen können oder sollten sie die Ordner gar nicht sehen dürfen?

Ich frage nur, weil wenn ich nen Video dazu mache, dann passt die ansicht nicht zu der, die wir im online VP haben.

Das betrifft auch die live version.

**Comment by pitpalme** [comment]
Wahrscheinlich ein Setup-Ding.
Einrichtungs-Manager müssen diese beiden "Ordner" nicht sehen und es muss nur die Einstellung geändert werden.

Wird evaluiert.

**Comment by pitpalme** [comment]
Still active? @uppzz

**Comment by pitpalme** [comment]
Solved
