### ISSUE TITLE
Send automatic email when a user signed up for a task

### ISSUE THREAD

**Issue by Doca** [coders4help/volunteer_planner#439]

**Comment by pitpalme** [comment]
Could create tons of mails (think about shift with 20 volunteers needed, several times a day).

Should be defined more detailed and clarified with respect of: what's the goal.

I. e. "sending mail to the user, containing .ics file for automatic calendar registration" vs. "facility shift managers are sent hundreds of e-mails a day".

**Comment by Doca** [comment]
If I would be a user and would receive a email with the date and location this would be a reminder (also when there will be a ics etc.) and enhance the probability that the volunteer is actually appearing. The number of emails sent shouldn't be that important if the service works :-D

**Comment by christophmeissner** [comment]
> If I would be a user and would receive a email with the date and location this would be a reminder (also when there will be a ics etc.) and enhance the probability that the volunteer is actually appearing. The number of emails sent shouldn't be that important if the service works :-D

Fancy updating the description and labels of the issue then?
