### ISSUE TITLE
For the unregistered, volunteer-planner.org will display facilities that do not currently have active shifts. 

### ISSUE THREAD

**Issue by uppzz** [coders4help/volunteer_planner#445]
For the unregistered, volunteer-planner.org will display facilities that do not currently have active shifts. After registration, these people then search for the facility - but cannot find it. 
It can look like cheating to outsiders. 
![Selection_453](https://user-images.githubusercontent.com/46990472/158418608-9475758d-2b1f-4850-bdac-d7b02ea06297.jpg)

![Selection_454](https://user-images.githubusercontent.com/46990472/158418738-65267946-7bb2-429e-b315-2e7afc479bd9.jpg)

**Comment by christophmeissner** [comment]
I can confirm. How should it be instead?

**Comment by pitpalme** [comment]
Even if no active shifts are offered / set up, people could inform about where to volunteer and maybe even contact facilities and offer help / suggest ideas or create a civil initiative.

PR wise it's more helpful to show, where help could be possible, to non-loggeed in users.

What's the gain of removing "currently not active" facilities?
Maybe facilities can become archived after a certain period of inactivity - and not shown on front page.
For at the moment awareness seems to outweight absolute precision.

**Comment by Doca** [comment]
I think if we take a user centered position (which we should I suppose?) and ask 1000 users if they think it's usable to see facilities you can't volunteer with or just see the once which have shifts (even if they are full already) the latter will by far win.

It's like when you buy sweets which says it has caramel inside but there isn't. What would be your picture of the company and product?

In my opinion it would make sense to just show facilities with currently have shifts. For PR reasons we could have a banner area on the main site with all associations we already worked with. Even from 2015

**Comment by pitpalme** [comment]
OK. Valid point.

What about finding a way to state "You can help" in "present" and "future" meaning and additionally state "and there's more / this locations, currently not actively searching, but maybe tomorrow"?

**Comment by Doca** [comment]
Could be useful to reorganize the main site in this way! Like "Currently A,B,C have no shifts but maybe in future. Check it out and keep updated"

**Comment by uppzz** [comment]
I feel like a fraud here.
When I buy something, I want to have what was on the package.
Maybe the facilities have merged some, maybe the facility no longer exists in the specified location. We can not know and to say that you can possibly help again I do not find good. the vp has made 10000 hours in a week. and if that was "only" with 10 facilities, then that shows me that the VP works very well. 
can you not do something like... if a facility has no shifts, then it is not shown?
we can leave it in the db in case the facilities want to use it again.

Translated with www.DeepL.com/Translator (free version)

**Comment by uppzz** [comment]
in any case, it should be written on the front, since when the VP is online again.
