### ISSUE TITLE
Is it possible to tie membership to a task?

### ISSUE THREAD

**Issue by uppzz** [coders4help/volunteer_planner#474]
**Is your idea or feature request related to a problem? Please describe.**
Example:
A facility creates 2 tasks, both are access restricted. Task 1 is playing with children and task 2 is food preparation. To be allowed to help with task 1 you need a police clearance certificate.
To help with task 2, you need a red card from the health department.

At the moment, if someone has this red card and becomes a member of the institution, he can also register for task 1, even if he has a negative police record.

At the moment, the only way to solve the problem is to make a separate facility for each restricted task. 

**Describe the solution you'd like**

Is it possible to tie membership to a task?

**Comment by pitpalme** [comment]
More general approach, discussed and dealt with in a different issue:

Facilities (or organizations) should be able to define attributes, which users can get assigned and than provide "proof of qualification".

Closing this one.
