### ISSUE TITLE
Django4 admin backend: colors in dark mode need correction

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#525]
**Describe the bug**
In dark mode (e. g. when system automatically switches by time of day) some colors make it hard to read text.

Example: Applying schedule template (see below).

Chances are, there's more places with defined colors, that don't take "prefers-color-schema" into account (yet).

**Screenshots**
![image](https://user-images.githubusercontent.com/748801/160411837-355b68ee-255a-4409-b6da-9f2a4c297f54.png)

**Additional context**
[](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
[](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#admin-theming)

**Comment by christophmeissner** [comment]
Is this the right screenshot? There seems to be no dark mode applied at all...

**Comment by pitpalme** [comment]
Good catch. It's been a test, if anybody actually reads descriptions. 😆 

Maybe upload auto-inverted colors, to make it readable?

![image](https://user-images.githubusercontent.com/748801/160593658-7fbf3af7-002c-4497-bcf7-acd21a1a049b.png)
![image](https://user-images.githubusercontent.com/748801/160593728-da25403c-a2ff-4a4b-b278-9ab4d85155e2.png)

**Comment by christophmeissner** [comment]
🤡
