### ISSUE TITLE
Django4: Facility manager can delete itself, then getting HTTP 403

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#527]

**Comment by pitpalme** [comment]
You're right. And if there would be a label "Bug" attached, it would have to be removed.

Expected behavior: catch 403, redirect to `/admin`.

**Comment by christophmeissner** [comment]
I think, redirecting admin users to '/admin' on a 403, misleads them into thinking something is broken, while in fact they just lack permissions. Somehow, we'd need to let the user know, that he was redirected to the admin home view because he tried to access a view without sufficient permissions.

**Comment by pitpalme** [comment]
What about creating a message, shown in UI, similar to

![image](https://user-images.githubusercontent.com/748801/160623303-39b4bec0-4881-4609-af5d-77210c26705e.png)
???

(As a facility manager open facility edit and click link to organization at the bottom, to reproduce this message ... something similar could be shown while redirecting to /admin/, stating "You don't have permission to view XXX members" ("... anymore"?).
