### ISSUE TITLE
Double check email address while registering

### ISSUE THREAD

**Issue by pitpalme** [coders4help/volunteer_planner#603]
**Is your idea or feature request related to a problem? Please describe.**
People register using mistyped email addresses.
This creates avoidable error messages and frustration because "register does not work, I'm not getting confirmation / activation mail".

**Describe the solution you'd like**
There should be some address checking, to avoid mistyped email addresses.
Most times it's a typo in email domain name (googlwmail.com, hormail.de, ...).
Either there's some java script checking mail address for at least domain reachability while entering and before submitting or there is a second email address input field, requiring users to enter address a second time - similar to password field, to avoid typos.
Of course it would be an error, if these two fields don't match.

**Describe alternatives you've considered**
Live with current state, error messages and level of frustration.

**Comment by cyroxx** [comment]
The second email address input field is a common pattern.

Domain reachability checking will cause headache with people who have their own domains.
Web- vs. mail server (A/AAAA records vs MX records), blocked ports (80/433 and ICMP), JS getting filtered by ad blockers are just some issues that come into my mind.
