### ISSUE TITLE
Clientpage - Registration: Possible to use badwords for registration

### ISSUE THREAD

**Issue by ufernandez** [coders4help/volunteer_planner#73]
Browser: Firefox  
Browser version: 40.0.3
Browser Language: English
Flash Player version: 18,0,0,232

Steps to Reproduce:
- create a new account
- use the badword "Arschloch" as username
- complete the registration process with valid datas

Description:
Instead of getting blocked by a message or a dialog, it is possible to use a badword (e.g. Arschloch) as username

Expected:
Badwords like "Arschloch", "Asshole", "Whore", "bitch" etc. should be blocked as usernames.

**Comment by chhantyal** [comment]
Interesting, not sure how to handle this or we should even consider to add such thing. Meanwhile, https://twitter.com/Arschloch

**Comment by christophmeissner** [comment]
I think, we need a policy for such things first, before thinking about solving it as a technical issue.

**Comment by DaniGr** [comment]
I suggest to follow ufuks advice and just blacklist those words. It will else create a bad environment for volunteers.

**Comment by jmewes** [comment]
How do you want to prevent "Arschloch" from using "_a_r_s_c_h_l_o_c_h_" etc. when his login name is rejected with a red popup window? Who would like to maintain such a list? Is one of the 13.000 users having such a name? I'd wait until this becomes a problem. The only way the prevent this would be a manual activation of users which is not the best way from a usability perspective.

**Comment by christophmeissner** [comment]
I think this is not a technical but a social problem, since we can not provide a blacklist for all bad words in all languages. Nor do I see a requirement to prematurely create a list and furthermore maintain said list of words we think are "bad words". If such a situation occurs, it will be decided on from case to case by community management instead of a filter robot.
